server:
    port: 8080

spring:
    application:
        name: demo
    datasource:
        url: jdbc:postgresql://localhost:5432/ecommerce
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format-sql: true
    liquibase:
        change-log: classpath:liquibase/db/changelog/master_changelog.xml
        

